apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: busybox
  namespace: default
spec:
  containers:
    - image: busybox
      name: pod
      command:
        - sleep
        - "1000"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
